"""empty message

Revision ID: 4f97e0ed9408
Revises: 59977494a5ab
Create Date: 2024-05-11 23:11:45.943813

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f97e0ed9408"
down_revision = "59977494a5ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("owner_type", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_owner_type"), ["owner_type"], unique=False
        )

    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index("ix_file_owner_id")
        batch_op.drop_index("ix_file_owner_type")

    op.drop_table("file")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "url",
            sa.VARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "owner_type",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at", sa.DATETIME(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="PK__file__3213E83FD305F738"),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_index("ix_file_owner_type", ["owner_type"], unique=False)
        batch_op.create_index("ix_file_owner_id", ["owner_id"], unique=False)

    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_owner_type"))
        batch_op.drop_index(batch_op.f("ix_document_owner_id"))

    op.drop_table("document")
    # ### end Alembic commands ###
