"""empty message

Revision ID: 59977494a5ab
Revises: a1ad35088f56
Create Date: 2024-05-11 23:02:45.253097

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59977494a5ab"
down_revision = "a1ad35088f56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("owner_type", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_file_owner_type"), ["owner_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_owner_type"))
        batch_op.drop_index(batch_op.f("ix_file_owner_id"))

    op.drop_table("file")
    # ### end Alembic commands ###
