"""empty message

Revision ID: 693e8e15df06
Revises: 042b850205a0
Create Date: 2024-04-16 12:58:25.396665

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "693e8e15df06"
down_revision = "042b850205a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_item", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
